{
  "formatVersion": "1.1",
  "component": {
    "group": "me.didit",
    "module": "didit-sdk",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "didit-sdk-3.3.1.aar",
          "url": "didit-sdk-3.3.1.aar",
          "size": 4257375,
          "sha512": "e8698dba85d126fac965ef22867f149530aea96d6f9a486241c23b4a27a68238800e52a9a4085d95b1d53de64634b9a889f8f03cbe7d346a5f4fb50c270176d3",
          "sha256": "8f9a483cb3e3c6adbc9e20cb9f4bdfff5fe0b233fb02eb10df7e153b04a8d82a",
          "sha1": "8fc74380df631faf90ff1db38b39b797e3eb6cf9",
          "md5": "f1dc84527e346bb143a022e3bc3aeaba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.mediapipe",
          "module": "tasks-vision",
          "version": {
            "requires": "0.10.29"
          }
        },
        {
          "group": "org.jmrtd",
          "module": "jmrtd",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "net.sf.scuba",
          "module": "scuba-sc-android",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "didit-sdk-3.3.1.aar",
          "url": "didit-sdk-3.3.1.aar",
          "size": 4257375,
          "sha512": "e8698dba85d126fac965ef22867f149530aea96d6f9a486241c23b4a27a68238800e52a9a4085d95b1d53de64634b9a889f8f03cbe7d346a5f4fb50c270176d3",
          "sha256": "8f9a483cb3e3c6adbc9e20cb9f4bdfff5fe0b233fb02eb10df7e153b04a8d82a",
          "sha1": "8fc74380df631faf90ff1db38b39b797e3eb6cf9",
          "md5": "f1dc84527e346bb143a022e3bc3aeaba"
        }
      ]
    }
  ]
}
